name: nekxolivro
description: Nekxo livro app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rflutter_alert: ^1.0.3
  pin_code_fields: ^2.5.1
  flutter_statusbarcolor: ^0.2.3
  flutter_sticky_header: ^0.4.2
  flutter_svg: ^0.17.4
  google_maps_flutter: ^0.5.26
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  fluttertoast: ^4.0.0
  progress_dialog: ^1.2.2
  libphonenumber: ^1.0.1
  font_awesome_flutter: ^8.8.1
  flutter_masked_text: ^0.8.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
  fonts:
    - family: JIcons
      fonts:
        - asset: assets/fonts/JIcons.ttf
    - family: Avenir-Book
      fonts:
        - asset: assets/fonts/Avenir-Book.otf
    - family: Avenir-Heavy
      fonts:
        - asset: assets/fonts/Avenir-Heavy.ttf
    - family: Avenir-Light
      fonts:
        - asset: assets/fonts/Avenir-Light.otf
    - family: AirbnbCereal-Book
      fonts:
        - asset: assets/fonts/AirbnbCereal-Book.ttf
    - family: AirbnbCereal-Light
      fonts:
        - asset: assets/fonts/AirbnbCereal-Light.ttf
    - family: AirbnbCereal-Medium
      fonts:
        - asset: assets/fonts/AirbnbCereal-Medium.ttf
    - family: Cera-Pro-Medium
      fonts:
        - asset: assets/fonts/Cera-Pro-Medium.otf
    - family: Cera-Pro-Light
      fonts:
        - asset: assets/fonts/Cera-Pro-Light.otf
    - family: Cera-Pro-Regular
      fonts:
        - asset: assets/fonts/Cera-Pro-Regular.otf
